"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_entra_auth",
    "apps.cla_auth",
    "apps.reports",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR.parent / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-local-development-only")

AUTH_USER_MODEL = "cla_auth.User"

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-gb"
TIME_ZONE = "Europe/London"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTHENTICATION_BACKENDS = ('apps.cla_auth.entra_backend.EntraBackend',)
ENTRA_AUTH = {
    "USERNAME_CLAIM": "USER_NAME",
    "BLOCK_GUEST_USERS": True,
    "VERSION": "v2.0",
    "SCOPES": os.environ.get("ENTRA_SCOPE", "").split(","),
    "CLIENT_ID": os.environ.get("ENTRA_CLIENT_ID", ""),
    "CLIENT_SECRET": os.environ.get("ENTRA_CLIENT_SECRET", ""),
    "TENANT_ID": os.environ.get("ENTRA_TENANT_ID", ""),
    "RELYING_PARTY_ID": os.environ.get("ENTRA_TENANT_ID", ""),
    # The audience should be your application ID
    "AUDIENCE": os.environ.get("ENTRA_AUDIENCE", ""),
    # Map Entra ID claims to Django user fields
    "CLAIM_MAPPING": {
        "first_name": "CLA_FIRST_NAME",
        "last_name": "CLA_LAST_NAME",
        "email": "USER_EMAIL"
    },
    # Optional: Enable group synchronization
    "GROUPS_CLAIM": "APP_ROLES",
    "MIRROR_GROUPS": True,
}
# Configure Django to use Entra ID login
LOGIN_URL = "django_entra_auth:login"
LOGIN_REDIRECT_URL = "/"
